language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - ng build --prod
deploy:
  provider: firebase
  token:
    secure: "1//0g7E-XZ0Kuw_DCgYIARAAGBASNwF-L9IrWKieKH2gtw7CJ1oGXd3rdCq4FDjG0uIbk_oVdyg4MzTOZbUWFPSR8z15RWT3aR3ESlk"
  project: "space-x-59933"
  message: "Hahahaha congratulation..."