language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
- ng build --prod --base-href https://kanchantyagi8.github.io/Space-X/
- firebase deploy